language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "jingniao"
  - git config user.email "gh0506@outlook.com"
  - git add .
  - git commit -m "build by travis"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
